"""Add ...

Revision ID: 55f8cbf5ed7b
Revises: 9f4caf2fe995
Create Date: 2026-09-03 14:41:51.927000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f8cbf5ed7b'
down_revision: Union[str, Sequence[str], None] = '9f4caf2fe995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset_size', sa.Integer(), nullable=False))
    op.alter_column('assets', 'asset_name',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'asset_name',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('assets', 'asset_size')
    # ### end Alembic commands ###
